# Generated by Django 5.2 on 2025-04-13 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_comments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
